# Generated by Django 6.0.6 on 2026-06-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LAPOAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('ippis_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('oracle_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=11)),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('loan_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_loan_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('monthly_repayment', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('loan_status', models.CharField(default='Active', max_length=50)),
                ('account_active', models.BooleanField(default=True)),
            ],
        ),
    ]
