# Generated by Django 6.0.6 on 2026-06-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('ippis_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('oracle_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('loan_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
        migrations.DeleteModel(
            name='LAPOAccount',
        ),
    ]
