# Generated by Django 6.0.6 on 2026-06-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loanaccount_delete_lapoaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('new_loan', 'New Loan'), ('top_up', 'Top Up Loan'), ('renewal', 'Renewal')], max_length=20)),
                ('bvn', models.CharField(max_length=11)),
                ('organisation_address', models.TextField()),
                ('surname', models.CharField(max_length=100)),
                ('other_names', models.CharField(max_length=100)),
                ('oracle_number', models.CharField(blank=True, max_length=50, null=True)),
                ('employment_date', models.DateField()),
                ('retirement_date', models.DateField(blank=True, null=True)),
                ('home_address', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('alternate_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('number_of_children', models.PositiveIntegerField(default=0)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('divorced', 'Divorced')], max_length=20)),
                ('id_type', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=100)),
                ('id_issued_date', models.DateField(blank=True, null=True)),
                ('id_expiry_date', models.DateField(blank=True, null=True)),
                ('next_of_kin_name', models.CharField(max_length=200)),
                ('next_of_kin_relationship', models.CharField(max_length=100)),
                ('next_of_kin_address', models.TextField()),
                ('next_of_kin_phone', models.CharField(max_length=20)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loan_tenor', models.CharField(max_length=50)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=3.12, max_digits=5)),
                ('monthly_net_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('account_number', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=200)),
                ('purpose_of_loan', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
